spring:
  profiles: prod
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate:
      temp:
        use_jdbc_metadata_defaults: false
server:
  port: ${PORT:5000}

---

spring:
  profiles: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop